# Generated by Django 5.0.6 on 2024-11-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('file_path', models.FileField(upload_to='csv_files/')),
                ('upload_status', models.BooleanField(default=False)),
                ('email_sent_status', models.BooleanField(default=False)),
                ('email_sent_to', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
