# Generated by Django 5.0.6 on 2024-11-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
