# Generated by Django 5.0.6 on 2024-11-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_files_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
