# Generated by Django 5.0.6 on 2024-11-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='input_file_path',
            field=models.FileField(blank=True, null=True, upload_to='input_files/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='csv_files/'),
        ),
    ]
