# Generated by Django 5.0.6 on 2024-11-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_files_input_file_path_alter_files_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='input_file_path',
            field=models.FileField(blank=True, null=True, upload_to='input_files/'),
        ),
    ]
