# Generated by Django 5.0.6 on 2024-11-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_archive_input_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='input_file_path',
            field=models.FileField(blank=True, null=True, upload_to='media/input_files/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='input_file_path',
            field=models.FileField(blank=True, null=True, upload_to='media/input_files/'),
        ),
    ]
