# Generated by Django 5.0.1 on 2024-12-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_edi_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edi_user_data',
            name='id_field',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
