# Generated by Django 5.0.1 on 2024-12-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_edi_user_data_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edi_user_data',
            name='ssn',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
