# Generated by Django 5.0.1 on 2024-12-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_edi_user_data_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edi_user_data',
            name='address1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='edi_user_data',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='edi_user_data',
            name='dob',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='edi_user_data',
            name='eff_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='edi_user_data',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='edi_user_data',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='edi_user_data',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
