# Generated by Django 5.0.1 on 2024-12-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_edi_user_data_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edi_user_data',
            name='custodial_address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
