# Generated by Django 5.0.1 on 2024-12-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_edi_user_data_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edi_user_data',
            name='custodial_parent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
