# Generated by Django 5.0.1 on 2024-12-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_edi_user_data_custodial_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='edi_user_data',
            name='temp_ssn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
