from django.db import models
import random
from django.utils import timezone


# Create your models here.

# class User(models.Model):
#     username = models.CharField(max_length=100, blank=True, null=True)
#     email = models.CharField(max_length=100, blank=True, null=True)
#     password = models.CharField(max_length=100, blank=True, null=True)

class User(models.Model):
    username = models.CharField(max_length=100, blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True, unique=True)
    otp = models.CharField(max_length=6, blank=True, null=True)
    last_otp_sent = models.DateTimeField(blank=True, null=True)

    def generate_otp(self):
        otp = f"{random.randint(100000, 999999)}"
        self.otp = otp
        self.last_otp_sent = timezone.now()
        self.save()
        return otp

class files(models.Model):
    file_name = models.CharField(max_length=100, blank=True, null=True)
    file_type = models.CharField(max_length=100, blank=True, null=True)
    file_date =models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, blank=True, null=True)
    file_path = models.FileField(upload_to='csv_files/',blank=True, null=True)
    upload_status = models.BooleanField(default=False)
    email_sent_status = models.BooleanField(default=False)
    email_sent_to = models.CharField(max_length=100, blank=True, null=True)
    input_file_path = models.FileField(upload_to='media/input_files/', blank=True, null=True)
    
    
class Archive(models.Model):
    file_name = models.CharField(max_length=100, blank=True, null=True)
    file_type = models.CharField(max_length=100, blank=True, null=True)
    file_date =models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, blank=True, null=True)
    file_path = models.FileField(upload_to='csv_files/')
    upload_status = models.BooleanField(default=False)
    email_sent_status = models.BooleanField(default=False)
    email_sent_to = models.CharField(max_length=100, blank=True, null=True)    
    input_file_path = models.FileField(upload_to='media/input_files/', blank=True, null=True)

class Employee(models.Model):
    EMDROP = models.CharField(max_length=10, blank=True, null=True)
    EMCLNT = models.CharField(max_length=10, blank=True, null=True)
    EMSSN = models.CharField(max_length=11, blank=True, null=True)
    EMMEM = models.CharField(max_length=10, blank=True, null=True)
    EMTEMP = models.BooleanField(default=False)
    EMRACF = models.CharField(max_length=10, blank=True, null=True)
    EMNAME = models.CharField(max_length=255, blank=True, null=True)
    EMADR1 = models.CharField(max_length=255, blank=True, null=True)
    EMADR2 = models.CharField(max_length=255, blank=True, null=True)
    EMADR3 = models.CharField(max_length=255, blank=True, null=True)
    EMADR4 = models.CharField(max_length=255, blank=True, null=True)
    EMCITY = models.CharField(max_length=100, blank=True, null=True)
    EMST = models.CharField(max_length=2, blank=True, null=True)
    EMZIP5 = models.CharField(max_length=5, blank=True, null=True)
    EMZIP4 = models.CharField(max_length=4, blank=True, null=True)
    EMZIP2 = models.CharField(max_length=2, blank=True, null=True)
    EMADRF = models.CharField(max_length=1, blank=True, null=True)
    EMNTYY = models.IntegerField(blank=True, null=True)
    EMNTMM = models.IntegerField(blank=True, null=True)
    EMNTDD = models.IntegerField(blank=True, null=True)
    EMDOBY = models.IntegerField(blank=True, null=True)
    EMDOBM = models.IntegerField(blank=True, null=True)
    EMDOBD = models.IntegerField(blank=True, null=True)
    EMDODY = models.IntegerField(blank=True, null=True)
    EMDODM = models.IntegerField(blank=True, null=True)
    EMDODD = models.IntegerField(blank=True, null=True)
    EMSEX = models.CharField(max_length=1, choices=[('M', 'Male'), ('F', 'Female')], blank=True, null=True)
    EMETHC = models.CharField(max_length=10, blank=True, null=True)
    EMMS = models.CharField(max_length=10, blank=True, null=True)
    EMMSYY = models.IntegerField(blank=True, null=True)
    EMMSMM = models.IntegerField(blank=True, null=True)
    EMMSDD = models.IntegerField(blank=True, null=True)
    EMSTCD = models.CharField(max_length=10, blank=True, null=True)
    EMPHON = models.CharField(max_length=15, blank=True, null=True)
    EMLOCL = models.CharField(max_length=10, blank=True, null=True)
    EMLLCL = models.CharField(max_length=10, blank=True, null=True)
    EMEMPR = models.CharField(max_length=10, blank=True, null=True)
    EMLPWY = models.IntegerField(blank=True, null=True)
    EMLPWM = models.IntegerField(blank=True, null=True)
    EMLPWD = models.IntegerField(blank=True, null=True)
    EMEMDY = models.IntegerField(blank=True, null=True)
    EMEMDM = models.IntegerField(blank=True, null=True)
    EMEMDD = models.IntegerField(blank=True, null=True)
    EMNEWH = models.BooleanField(default=False)
    EMJOB = models.CharField(max_length=100, blank=True, null=True)
    EMJEDY = models.IntegerField(blank=True, null=True)
    EMJEDM = models.IntegerField(blank=True, null=True)
    EMJEDD = models.IntegerField(blank=True, null=True)
    EMUSR1 = models.CharField(max_length=50, blank=True, null=True)
    EMUSR2 = models.CharField(max_length=50, blank=True, null=True)
    EMUSR3 = models.CharField(max_length=50, blank=True, null=True)
    EMUSR4 = models.CharField(max_length=50, blank=True, null=True)
    EMUSR5 = models.CharField(max_length=50, blank=True, null=True)
    EMUSR6 = models.CharField(max_length=50, blank=True, null=True)
    EMUS1Y = models.IntegerField(blank=True, null=True)
    EMUS1M = models.IntegerField(blank=True, null=True)
    EMUS1D = models.IntegerField(blank=True, null=True)
    EMUS2Y = models.IntegerField(blank=True, null=True)
    EMUS2M = models.IntegerField(blank=True, null=True)
    EMUS2D = models.IntegerField(blank=True, null=True)
    EMUS3Y = models.IntegerField(blank=True, null=True)
    EMUS3M = models.IntegerField(blank=True, null=True)
    EMUS3D = models.IntegerField(blank=True, null=True)
    EMUS4Y = models.IntegerField(blank=True, null=True)
    EMUS4M = models.IntegerField(blank=True, null=True)
    EMUS4D = models.IntegerField(blank=True, null=True)
    EMUS5Y = models.IntegerField(blank=True, null=True)
    EMUS5M = models.IntegerField(blank=True, null=True)
    EMUS5D = models.IntegerField(blank=True, null=True)
    EMUS6Y = models.IntegerField(blank=True, null=True)
    EMUS6M = models.IntegerField(blank=True, null=True)
    EMUS6D = models.IntegerField(blank=True, null=True)
    EMCRYY = models.IntegerField(blank=True, null=True)
    EMCRMM = models.IntegerField(blank=True, null=True)
    EMCRDD = models.IntegerField(blank=True, null=True)
    EMUPYY = models.IntegerField(blank=True, null=True)
    EMUPMM = models.IntegerField(blank=True, null=True)
    EMUPDD = models.IntegerField(blank=True, null=True)
    EMUSER = models.CharField(max_length=50, blank=True, null=True)
    file_date = models.CharField(max_length=50,null=True)



class Dependent(models.Model):
    DPDROP = models.CharField(max_length=10, blank=True, null=True)
    DPCLNT = models.CharField(max_length=10, blank=True, null=True)
    DPSSN = models.CharField(max_length=11, blank=True, null=True)
    DPSEQ = models.CharField(max_length=10, blank=True, null=True)
    DPNAME = models.CharField(max_length=255, blank=True, null=True)
    DPDOBY = models.IntegerField(blank=True, null=True)
    DPDOBM = models.IntegerField(blank=True, null=True)
    DPDOBD = models.IntegerField(blank=True, null=True)
    DPDODY = models.IntegerField(blank=True, null=True)
    DPDODM = models.IntegerField(blank=True, null=True)
    DPDODD = models.IntegerField(blank=True, null=True)
    DPDSSN = models.CharField(max_length=11, blank=True, null=True)
    DPSEX = models.CharField(max_length=1, choices=[('M', 'Male'), ('F', 'Female')], blank=True, null=True)
    DPTYPE = models.CharField(max_length=10, blank=True, null=True)
    DPRLTN = models.CharField(max_length=10, blank=True, null=True)
    DPEFDY = models.IntegerField(blank=True, null=True)
    DPEFDM = models.IntegerField(blank=True, null=True)
    DPEFDD = models.IntegerField(blank=True, null=True)
    DPTDTY = models.IntegerField(blank=True, null=True)
    DPTDTM = models.IntegerField(blank=True, null=True)
    DPTDTD = models.IntegerField(blank=True, null=True)
    DPCOB = models.CharField(max_length=10, blank=True, null=True)
    DPPLAN = models.CharField(max_length=10, blank=True, null=True)
    DPCLAS = models.CharField(max_length=10, blank=True, null=True)
    DPSTAT = models.CharField(max_length=10, blank=True, null=True)
    DPALTP = models.CharField(max_length=10, blank=True, null=True)
    DPSELF = models.BooleanField(default=False)
    DPMDFL = models.BooleanField(default=False)
    DPMEFY = models.IntegerField(blank=True, null=True)
    DPMEFM = models.IntegerField(blank=True, null=True)
    DPMEFD = models.IntegerField(blank=True, null=True)
    DPMGYY = models.IntegerField(blank=True, null=True)
    DPMGMM = models.IntegerField(blank=True, null=True)
    DPMGDD = models.IntegerField(blank=True, null=True)
    DPDVYY = models.IntegerField(blank=True, null=True)
    DPDVMM = models.IntegerField(blank=True, null=True)
    DPDVDD = models.IntegerField(blank=True, null=True)
    DPBSFL = models.BooleanField(default=False)
    DPDSFL = models.BooleanField(default=False)
    DPMGFL = models.BooleanField(default=False)
    DPDVFL = models.BooleanField(default=False)
    DPCRYY = models.IntegerField(blank=True, null=True)
    DPCRMM = models.IntegerField(blank=True, null=True)
    DPCRDD = models.IntegerField(blank=True, null=True)
    DPUPYY = models.IntegerField(blank=True, null=True)
    DPUPMM = models.IntegerField(blank=True, null=True)
    DPUPDD = models.IntegerField(blank=True, null=True)
    DPUSER = models.CharField(max_length=50, blank=True, null=True)
    file_date = models.CharField(max_length=50,null=True)


class Eligibility(models.Model):
    ELDROP = models.CharField(max_length=10, blank=True, null=True)
    ELCLNT = models.CharField(max_length=10, blank=True, null=True)
    ELSSN = models.CharField(max_length=11, blank=True, null=True)
    ELDSEQ = models.CharField(max_length=10, blank=True, null=True)
    ELEPDY = models.IntegerField(blank=True, null=True)
    ELEPDM = models.IntegerField(blank=True, null=True)
    ELEPDD = models.IntegerField(blank=True, null=True)
    ELCOBF = models.BooleanField(default=False)
    ELPLAN = models.CharField(max_length=10, blank=True, null=True)
    ELCLAS = models.CharField(max_length=10, blank=True, null=True)
    ELHSTA = models.CharField(max_length=10, blank=True, null=True)
    ELWSTA = models.CharField(max_length=10, blank=True, null=True)
    ELTYP = models.CharField(max_length=10, blank=True, null=True)
    ELHRS = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ELEMPR = models.CharField(max_length=10, blank=True, null=True)
    ELHIFC = models.CharField(max_length=10, blank=True, null=True)
    ELUDTY = models.IntegerField(blank=True, null=True)
    ELUDTM = models.IntegerField(blank=True, null=True)
    ELUDTD = models.IntegerField(blank=True, null=True)
    ELUSER = models.CharField(max_length=50, blank=True, null=True)
    ELTIME = models.TimeField(blank=True, null=True)
    file_date = models.CharField(max_length=50,null=True)

class EDI834Data(models.Model):
    group_id = models.IntegerField(default=0)
    ISA = models.CharField(max_length=255, null=True, blank=True)
    GS = models.CharField(max_length=255, null=True, blank=True)
    ST = models.CharField(max_length=255, null=True, blank=True)
    BGN = models.CharField(max_length=255, null=True, blank=True)
    DTP = models.CharField(max_length=255, null=True, blank=True)
    N1 = models.CharField(max_length=255, null=True, blank=True)
    INS = models.CharField(max_length=255, null=True, blank=True)
    REF = models.CharField(max_length=255, null=True, blank=True)
    NM1 = models.CharField(max_length=255, null=True, blank=True)
    PER = models.CharField(max_length=255, null=True, blank=True)
    N3 = models.CharField(max_length=255, null=True, blank=True)
    N4 = models.CharField(max_length=255, null=True, blank=True)
    DMG = models.CharField(max_length=255, null=True, blank=True)
    HD = models.CharField(max_length=255, null=True, blank=True)
    SE = models.CharField(max_length=255, null=True, blank=True)
    GE = models.CharField(max_length=255, null=True, blank=True)
    IEA = models.CharField(max_length=255, null=True, blank=True)
    CreatedDate = models.DateTimeField(auto_now_add=True)


class EDI_USER_DATA(models.Model):
    last_name = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    ssn = models.CharField(max_length=11, null=True)
    sub_dep = models.CharField(max_length=50)
    status = models.CharField(max_length=50)
    type = models.CharField(max_length=50)
    phone = models.CharField(max_length=15, blank=True, null=True)
    address1 = models.CharField(max_length=255,null=True)
    city = models.CharField(max_length=100, null=True)
    state = models.CharField(max_length=100, null=True)
    zip = models.CharField(max_length=10, null=True)
    dob = models.CharField(max_length=255,null=True)
    sex = models.CharField(max_length=1, choices=[('M', 'Male'), ('F', 'Female')], null=True)
    plan = models.CharField(max_length=100, blank=True, null=True)
    class_field = models.CharField(max_length=100, blank=True, null=True)
    eff_date = models.CharField(max_length=255,null=True)
    id_field = models.CharField(max_length=100,null=True)  
    dep_first_name = models.CharField(max_length=100, blank=True, null=True)
    dep_last_name = models.CharField(max_length=100, blank=True, null=True)
    dep_dob = models.DateField(blank=True, null=True)
    dep_ssn = models.CharField(max_length=11, blank=True, null=True)
    dep_sex = models.CharField(max_length=1, choices=[('M', 'Male'), ('F', 'Female')], blank=True, null=True)
    custodial_parent = models.CharField(max_length=255, blank=True, null=True)
    custodial_address1 = models.CharField(max_length=255, blank=True, null=True)
    custodial_address2 = models.CharField(max_length=255, blank=True, null=True)
    custodial_city = models.CharField(max_length=100, blank=True, null=True)
    custodial_state = models.CharField(max_length=100, blank=True, null=True)
    custodial_zip = models.CharField(max_length=10, blank=True, null=True)
    custodial_phone = models.CharField(max_length=15, blank=True, null=True)
    address2 = models.CharField(max_length=255, blank=True, null=True)
    member_id = models.CharField(max_length=255, blank=True, null=True)
    date_edi = models.CharField(max_length=255, blank=True, null=True)
    temp_ssn = models.CharField(max_length=255, blank=True, null=True)